# Generated by Django 2.0.4 on 2018-05-15 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation', models.IntegerField(default=0, verbose_name='毕业学分')),
                ('obtain', models.IntegerField(default=0, verbose_name='已修学分')),
                ('need', models.IntegerField(default=0, verbose_name='所需学分')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25, verbose_name='姓名')),
                ('no', models.CharField(max_length=25, verbose_name='学号')),
                ('classno', models.CharField(default='', max_length=25, verbose_name='班级号')),
                ('type', models.IntegerField(choices=[(1, '事假'), (2, '病假'), (3, '其他')], default=3)),
                ('time', models.CharField(default='', max_length=100, verbose_name='请假时间')),
                ('reason', models.CharField(default='', max_length=100, verbose_name='请假原因')),
                ('is_back', models.IntegerField(choices=[(1, '未销假'), (2, '已销假')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorce', models.CharField(default='', max_length=125, verbose_name='成绩图片url')),
                ('cadre', models.CharField(default='', max_length=125, verbose_name='干部任职情况图片url')),
                ('reward_punish', models.CharField(default='', max_length=125, verbose_name='奖惩情况图片url')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '推免保送'), (2, '考研深造'), (3, '出国留学'), (4, '就业'), (5, '应征入伍')], default=4)),
                ('point', models.IntegerField(default=0, verbose_name='指定老师id')),
                ('desc', models.CharField(default='', max_length=500, verbose_name='问题描述')),
                ('is_answered', models.IntegerField(default=0)),
                ('reply', models.CharField(default='', max_length=500, verbose_name='回答')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25, verbose_name='姓名')),
                ('no', models.CharField(max_length=25, unique=True, verbose_name='学号')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '未知')], default=3)),
                ('identity', models.CharField(default='', max_length=25, verbose_name='身份证号')),
                ('nation', models.CharField(default='汉族', max_length=25, verbose_name='民族')),
                ('major', models.CharField(default='', max_length=25, verbose_name='专业')),
                ('zone', models.IntegerField(choices=[(1, '马区'), (2, '余区'), (3, '未知')], default=1)),
                ('classno', models.CharField(default='', max_length=25, verbose_name='班级号')),
                ('counsellor', models.CharField(default='', max_length=25, verbose_name='辅导员职工号')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(default='', max_length=25, verbose_name='职工号')),
                ('name', models.CharField(default='', max_length=25, verbose_name='姓名')),
                ('intro', models.CharField(default='', max_length=500, verbose_name='介绍')),
                ('college', models.CharField(default='', max_length=25, verbose_name='所属学院')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=25, verbose_name='密码')),
                ('type', models.IntegerField(choices=[(1, '管理员（辅导员）'), (2, '学生'), (3, '教师'), (4, '超级管理员')], default=2)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infosys.Student'),
        ),
        migrations.AddField(
            model_name='query',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infosys.Student'),
        ),
        migrations.AddField(
            model_name='credit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infosys.Student'),
        ),
    ]
